### ISSUE TITLE
如何使用，提供说明文档

### ISSUE THREAD

**Issue by luowei729** [babaohuang/GeminiProChat#1]
### Describe the feature

如何使用，提供说明文档

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by CR23-Yzlong** [comment]
你看 readme_cn 啊 他是基于 GPT的项目改的

**Comment by CR23-Yzlong** [comment]
https://github.com/babaohuang/GeminiProChat/blob/main/README.zh-CN.md

**Comment by luowei729** [comment]
> 你看 readme_cn 啊 他是基于 GPT的项目改的

.env只要配置API key吗，我只配置不能正常使用

**Comment by babaohuang** [comment]
请稍后，今天等我把bug修复好了之后更新说明文档
