### ISSUE TITLE
Need socks5 proxy support 

### ISSUE THREAD

**Issue by Alex-coffen** [babaohuang/GeminiProChat#13]
### Describe the feature

Want to use sock5 proxy instead of https proxy

### Additional context

Want to use sock5 proxy instead of https proxy

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by babaohuang** [comment]
You can try `API_BASE_URL`, check [here](https://github.com/babaohuang/GeminiProChat?tab=readme-ov-file#solution-for-user-location-is-not-supported-for-the-api-use) to see how to deploy a gemini proxy on Vercel.
