### ISSUE TITLE
为什么我部署了之后就可以直接聊天了？我的apikey都还没添加呢。

### ISSUE THREAD

**Issue by GreysonHYH** [babaohuang/GeminiProChat#143]
### Additional context

我按照README中的Vercel部署了之后，打开Vercel提供的链接，直接就可以聊天成功了。 可是代码中没有任何的apikey呀，所以这个成功聊天用的是哪个apikey？有点不理解。有人可以给解释下吗？感谢。
![image](https://github.com/babaohuang/GeminiProChat/assets/105972575/25296c71-68f9-4515-b538-2d33066bf314)

**Comment by whengu** [comment]
盗号了?
