### ISSUE TITLE
User location not supported for the API use.

### ISSUE THREAD

**Issue by pei92** [babaohuang/GeminiProChat#16]
### How is Gemini Pro Chat deployed?

Vercel

### Describe the bug

部署到Vercel后，打开提示User location not supported for the API use.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by antergone** [comment]
自己部署一个Vercel Edge，把Base URL换了即可。https://simonmy.com/posts/使用vercel反向代理google-palm-api.html

**Comment by babaohuang** [comment]
> 自己部署一个Vercel Edge，把Base URL换了即可。[https://simonmy.com/posts/使用vercel反向代理google-palm-api.html](https://simonmy.com/posts/%E4%BD%BF%E7%94%A8vercel%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86google-palm-api.html)

感谢大佬提供的解决方案！完美解决了User location not supported for the API use.问题！
