### ISSUE TITLE
HTTPS Proxy isn't working

### ISSUE THREAD

**Issue by Alex-coffen** [babaohuang/GeminiProChat#20]
### What operating system are you using?

Linux - Docker

### What browser are you using?

Chrome

### Describe the bug

When I put "HTTPS_PROXY=socks5://192.168.0.1:28081" in both docker commandline and .env, the proxy won't take any action. It doesn't work

### What prompt did you enter?

Default

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by babaohuang** [comment]
Sorry for the mistake, `HTTPS_PROXY` is not supported. You can try `API_BASE_URL`, check [here](https://github.com/babaohuang/GeminiProChat?tab=readme-ov-file#solution-for-user-location-is-not-supported-for-the-api-use) to see how to deploy a gemini proxy on Vercel.
