### ISSUE TITLE
How to use the API_BASE_URL?

### ISSUE THREAD

**Issue by siyehua** [babaohuang/GeminiProChat#22]
### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the bug

我使用vercel 创建好之后，使用会提示：
然后我在自己的仓库里，新建了一个文件`.env`,在里面写：User location is not supported for the API use.
`API_BASE_URL=https://google-genmini-pro.vercel.app/`
然后回到 vercel ，发现它自己重新构建了，构建完成后，仍然提示：User location is not supported for the API use.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by babaohuang** [comment]
看 [这里](https://github.com/babaohuang/GeminiProChat?tab=readme-ov-file#solution-for-user-location-is-not-supported-for-the-api-use) 自己部署一个gemini proxy，然后把部署好的域名填到`API_BASE_URL`，填好环境变量后要redeploy一下才生效

**Comment by siyehua** [comment]
我就是用了你说的这个，在设置里加了：
<img width="1487" alt="image" src="https://github.com/babaohuang/GeminiProChat/assets/9376247/4ec66363-702d-46e1-a734-78d6ccdae558">
然后重新构建，构建之后提示：

<img width="720" alt="image" src="https://github.com/babaohuang/GeminiProChat/assets/9376247/0d287b95-b264-47ae-9224-129b925a047b">

然后我看请求也没发错，就是我设置的这个：
<img width="484" alt="image" src="https://github.com/babaohuang/GeminiProChat/assets/9376247/56cc7b68-f315-4949-b42f-ed7e52bae09c">

**Comment by siyehua** [comment]
@babaohuang
