### ISSUE TITLE
回复当前时间不对

### ISSUE THREAD

**Issue by cookielb** [babaohuang/GeminiProChat#34]
### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the bug

回复当前时间不对（部署在vercel）

### What prompt did you enter?

what's the time now

目前时间是：2023年3月8日 星期三 下午9:38:08 CST

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by babaohuang** [comment]
大语言模型就是这样的。

**Comment by CA-GPT** [comment]
同样的问题，部署在 vercel 时间不对
