### ISSUE TITLE
API_BASE_URL=这个到底填啥 为什么填什么都不对啊  

### ISSUE THREAD

**Issue by b002200** [babaohuang/GeminiProChat#36]
### What operating system are you using?

win

### What browser are you using?

谷歌

### Describe the bug

Error
[GoogleGenerativeAI Error]: Error fetching from fetch failed

### What prompt did you enter?

聊天后报错闪退 Error
[GoogleGenerativeAI Error]: Error fetching from fetch failed

### Console Logs

闪退

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by babaohuang** [comment]
请查看[这里的说明](https://github.com/babaohuang/GeminiProChat#solution-for-user-location-is-not-supported-for-the-api-use)部署一个自己的`API_BASE_URL`

**Comment by 7noemo** [comment]
> 请查看[这里的说明](https://github.com/babaohuang/GeminiProChat#solution-for-user-location-is-not-supported-for-the-api-use)部署一个自己的`API_BASE_URL`

![image](https://github.com/babaohuang/GeminiProChat/assets/103473489/27b85b76-f5a7-4381-9c99-238d09c108e9)
部署了一个URL 填进去报错了

**Comment by 7noemo** [comment]
> > 请查看[这里的说明](https://github.com/babaohuang/GeminiProChat#solution-for-user-location-is-not-supported-for-the-api-use)部署一个自己的`API_BASE_URL`
> 
> ![image](https://private-user-images.githubusercontent.com/103473489/292135298-27b85b76-f5a7-4381-9c99-238d09c108e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDYyNjMsIm5iZiI6MTcwMzE0NTk2MywicGF0aCI6Ii8xMDM0NzM0ODkvMjkyMTM1Mjk4LTI3Yjg1Yjc2LWY1YTctNDM4MS05Yzk5LTIzOGQwOWMxMDhlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwODA2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGQ0ZjVhYTVkMmJjMjE3NDk1ODZmMGVlMzliN2QxOGQxM2JhMWExNjIwZDNkZDkyMDU0OGMxYmI0ZmU4YjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pa28wKB04T89SgHbV3eXiOfzYDC1SbsFOLz6Dszojh4) 部署了一个URL 填进去报错了

填了另外的带用户名的地址就行了。

**Comment by gitx6** [comment]
> > > 请查看[这里的说明](https://github.com/babaohuang/GeminiProChat#solution-for-user-location-is-not-supported-for-the-api-use)部署一个自己的`API_BASE_URL`
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/103473489/292135298-27b85b76-f5a7-4381-9c99-238d09c108e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDYyNjMsIm5iZiI6MTcwMzE0NTk2MywicGF0aCI6Ii8xMDM0NzM0ODkvMjkyMTM1Mjk4LTI3Yjg1Yjc2LWY1YTctNDM4MS05Yzk5LTIzOGQwOWMxMDhlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwODA2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGQ0ZjVhYTVkMmJjMjE3NDk1ODZmMGVlMzliN2QxOGQxM2JhMWExNjIwZDNkZDkyMDU0OGMxYmI0ZmU4YjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pa28wKB04T89SgHbV3eXiOfzYDC1SbsFOLz6Dszojh4) 部署了一个URL 填进去报错了
> 
> 填了另外的带用户名的地址就行了。

我也碰到同样的问题，你是添加哪个带用户名的地址解决的？谢谢。
