### ISSUE TITLE
Support hosting on cloudflare workers

### ISSUE THREAD

**Issue by harryzcy** [babaohuang/GeminiProChat#38]
### Describe the feature

Support using [Cloudflare workers](https://developers.cloudflare.com/workers/) instead of Vercel

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by babaohuang** [comment]
Why not Vercel ? Vercel is free.

**Comment by harryzcy** [comment]
> Why not Vercel ? Vercel is free.

Just to say an alternative, and because I have many other projects hosted on Cloudflare

**Comment by babaohuang** [comment]
OK , I will try
