### ISSUE TITLE
输入后无反馈，send按钮无反馈

### ISSUE THREAD

**Issue by z50913** [babaohuang/GeminiProChat#4]
### What operating system are you using?

win2012

### What browser are you using?

firefox  edge

### Describe the bug

![image](https://github.com/babaohuang/GeminiProChat/assets/78022659/8d6c8e36-6fab-49d4-9875-6ec401c112f2)

### What prompt did you enter?

搭建好可以访问页面，但是打字按enter没有发送出去，而是切换到下一行，按send也没反应，通用的环境浏览器测试博主的可以正常返回信息

### Console Logs

无

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by z50913** [comment]
也没报错

**Comment by JinChengneng** [comment]
我也碰到了这个问题。

**Comment by xinstar-2021** [comment]
我也遇到了这个问题，通过域名反代访问环境就不行了，后台没接收到数据，前台的点击事件没有被触发

**Comment by Mrered** [comment]
> 我也遇到了这个问题，通过域名反代访问环境就不行了，后台没接收到数据，前台的点击事件没有被触发

同样的情况，直接用 Vercel 的域名就可以发送，用自己域名 CNAME 就无法发送

**Comment by JinChengneng** [comment]
> > 我也遇到了这个问题，通过域名反代访问环境就不行了，后台没接收到数据，前台的点击事件没有被触发
> 
> 同样的情况，直接用 Vercel 的域名就可以发送，用自己域名 CNAME 就无法发送

是的，我也是这样

**Comment by babaohuang** [comment]
> > 我也遇到了这个问题，通过域名反代访问环境就不行了，后台没接收到数据，前台的点击事件没有被触发
> 
> 同样的情况，直接用 Vercel 的域名就可以发送，用自己域名 CNAME 就无法发送

试一下解析域名的时候用这个方案：

A记录地址：76.223.126.88

CNAME 记录地址：cname-china.vercel-dns.com

**Comment by Mrered** [comment]
> > > 我也遇到了这个问题，通过域名反代访问环境就不行了，后台没接收到数据，前台的点击事件没有被触发
> > 
> > 
> > 同样的情况，直接用 Vercel 的域名就可以发送，用自己域名 CNAME 就无法发送
> 
> 试一下解析域名的时候用这个方案：
> 
> A记录地址：76.223.126.88
> 
> CNAME 记录地址：cname-china.vercel-dns.com

测试过程：

- 修改 CNAME 记录为 cname-china.vercel-dns.com ，无效
- 修改 A 记录为 76.223.126.88 会导致 User location is not supported for the API use
- 在已部署项目上添加自建的代理 API_BASE_URL 变量后重新部署会导致无法访问
- 删掉旧的从头开始部署新项目，并添加 API_BASE_URL 变量，会导致回到最初的状态，即仅可通过 Vercel 给的域名访问，无法通过 CNAME 域名访问。

**Comment by Mrered** [comment]
> CF添加解析记录的时候，有设置代理模式吗？把代理模式去掉试试看，改为仅DNS.

回楼上： CF 代理模式关闭和打开都不行。

- - - 

现在好了
