### ISSUE TITLE
docker-compose.yml 直接下载后部署报错     修改container_name: geminiprochat 为image: howie6879/geminiprochat:v0.1.0 后部署正常

### ISSUE THREAD

**Issue by brucelau1987cn** [babaohuang/GeminiProChat#40]
### How is Gemini Pro Chat deployed?

Node

### Describe the bug

[+] Building 0.1s (2/2) FINISHED                                                     docker:default
 => [geminiprochat internal] load build definition from Dockerfile                             0.0s
 => => transferring dockerfile: 2B                                                             0.0s
 => [geminiprochat internal] load .dockerignore                                                0.0s
 => => transferring context: 2B                                                                0.0s
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3775294946/Dockerfile: no such file or directory

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by antergone** [comment]
经过实际测试，最新版本没有问题，你给出的命令是拉取其他开发者发布的远端的镜像。
可以尝试以下命令：
```shell
# 清理缓存
docker builder prune
# 启动服务
docker-compose up
```

**Comment by brucelau1987cn** [comment]
version: '3'

services:
  geminiprochat:
    image: 'babaohuang/geminiprochat:latest'
    container_name: geminiprochat
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=YOUR_GEMINI_API_KEY
      # - HTTPS_PROXY=YOUR_HTTPS_PROXY
      # - API_BASE_URL=YOUR_GEMINI_API_BASE_URL
      # - HEAD_SCRIPTS=YOUR_HEAD_SCRIPTS
      # - PUBLIC_SECRET_KEY=YOUR_SECRET_KEY
      # - SITE_PASSWORD=YOUR_SITE_PASSWORD
      # - OPENAI_API_MODEL=YOUR_OPENAI_API_MODEL



改成这样 完美解决
