### ISSUE TITLE
不能回答正确的问题？

### ISSUE THREAD

**Issue by xiaoliwe** [babaohuang/GeminiProChat#45]
### What operating system are you using?

Online

### What browser are you using?

Edge

### Describe the bug

绑定 Gemini Pro 的 API 后,回答今天的日期都出错？
<img width="357" alt="Screenshot 2023-12-20 at 16 13 02" src="https://github.com/babaohuang/GeminiProChat/assets/9930176/0874654a-fe8a-4a76-bc8f-814224b2b09f">

### What prompt did you enter?

what's of today?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by xiaoliwe** [comment]
类似的问题
![Uploading Screenshot 2023-12-20 at 16.15.30.png…]()

**Comment by xiaoliwe** [comment]
类似的问题
<img width="583" alt="Screenshot 2023-12-20 at 16 15 30" src="https://github.com/babaohuang/GeminiProChat/assets/9930176/0a5d9b81-cd61-4272-8418-9c02360b2e9f">

**Comment by babaohuang** [comment]
因为Gemini pro 的API本身就不会联网，它只是一个语言模型

**Comment by xiaoliwe** [comment]
理解错了, 默认Gemini Pro 是可以联网处理任务的模型...
