### ISSUE TITLE
求教如何部署https

### ISSUE THREAD

**Issue by KittenCN** [babaohuang/GeminiProChat#46]
### Describe the feature

求教如何部署https

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by babaohuang** [comment]
部署在Vercel上就是默认https的呀

**Comment by KittenCN** [comment]
我是部署在我自己的服务器上了。。

**Comment by ruixing1001** [comment]
用宝塔反代可以

**Comment by 2168028160** [comment]
Both Nginx and Apache HTTP Server are suitable options. If you don't know how to set them up, feel free to ask the chatbot for assistance.

**Comment by KittenCN** [comment]
> Both Nginx and Apache HTTP Server are suitable options. If you don't know how to set them up, feel free to ask the chatbot for assistance.

ok, got it, thx

**Comment by pankejia2000** [comment]
pnpm run dev --host --https    然后在Cloudflare配置反带代就好。

**Comment by fanqieniuroutang** [comment]
LZ操作成功了吗？我用nginx卡壳了，通过vim编辑器输入配置信息后没有成功

**Comment by karateservant** [comment]
nginx 反向代理就行

server {

        listen 80 ;
        listen [::]:80 ;
        server_name xxxxxxxx.com;

        location / {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_pass         "http://127.0.0.1:3000";
        }

}

**Comment by KittenCN** [comment]
直接用宝塔，有专门的设置界面，很容易的
