### ISSUE TITLE
vercel部署只填入了谷歌的gemini api 当问到他是谁开发时，有概率出现他是百度开发的 

### ISSUE THREAD

**Issue by KrisFlowerss** [babaohuang/GeminiProChat#6]
### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the bug

蛮奇怪的

### What prompt did you enter?

你是谁开发的

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by babaohuang** [comment]
😄那是大语言模型的幻觉
