### ISSUE TITLE
send按钮无法点击

### ISSUE THREAD

**Issue by pj876609908** [babaohuang/GeminiProChat#66]
### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the bug

请教大佬，我在vps docker 以及vercel中都部署了， 我总是试图通过自己的域名访问，但是在使用自己的域名访问中都出现send按钮无法点击发送，但是使用ip地址或者是使用vercel提供的域名都能访问并使用send按钮发送获得回复，这是什么问题呢？

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tanmx** [comment]
同样的问题，vercel 自定义域名send没有反应，用自动生成的域名正常

**Comment by acche** [comment]
同样的问题，vercel 自定义域名send没有反应，用自动生成的域名正常

**Comment by tanmx** [comment]
> 同样的问题，vercel 自定义域名send没有反应，用自动生成的域名正常

用这个proxy就可以了

https://github.com/antergone/palm-proxy

**Comment by acche** [comment]
> > 同样的问题，vercel 自定义域名send没有反应，用自动生成的域名正常
> 
> 用这个proxy就可以了
> 
> https://github.com/antergone/palm-proxy

用Netlify那个吗? @tanmx

**Comment by acche** [comment]
> > 同样的问题，vercel 自定义域名send没有反应，用自动生成的域名正常
> 
> 用这个proxy就可以了
> 
> https://github.com/antergone/palm-proxy

没效果，点击send依然无效

**Comment by tanmx** [comment]
> > > 同样的问题，vercel 自定义域名send没有反应，用自动生成的域名正常
> > 
> > 
> > 用这个proxy就可以了
> > https://github.com/antergone/palm-proxy
> 
> 没效果，点击send依然无效

这个 proxy 得部署到 vercel

**Comment by tanmx** [comment]
> https://github.com/antergone/palm-proxy

我不确定，反正我用vercel部署这个proxy https://github.com/antergone/palm-proxy，自定义域名正常了

**Comment by acche** [comment]
我这里要在CF里设置DNS only 就可以了.

**Comment by tjsky** [comment]
> 我这里要在CF里设置DNS only 就可以了.

应该就是CDN的缓存问题，CF设置为开发模式绕过缓存就好了。

**Comment by pj876609908** [comment]
> 我这里要在CF里设置DNS only 就可以了.

我也是通过dns only 好了。
