### ISSUE TITLE
布置了代理（palm-proxy）出错

### ISSUE THREAD

**Issue by hprandom** [babaohuang/GeminiProChat#69]
### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the bug

没有布置plam-proxy时，部署成功，但是显示 "User location is not supported for the API use"。
于是我按照Note部署了palm-proxy，重新部署，出现了新的出错提示：
Error
[GoogleGenerativeAI Error]: Error fetching from palm-proxy-gemini-silk.vercel.app/v1/models/gemini-pro:streamGenerateContent?alt=sse: Invalid URL string.
能否请教或者提示一下，我该如何解决这个问题？谢谢了。

### What prompt did you enter?

palm-proxy部署显示成功后，vercel中网页缩略图显示的404……

![Clip_20231222_110638](https://github.com/babaohuang/GeminiProChat/assets/48062021/388ec66b-650b-4a1d-8c09-b16386a0599c)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by stefan-ysh** [comment]
能否提供下具体配置信息或截图

**Comment by babaohuang** [comment]
palm-proxy 部署后直接访问域名出现这个404是正常的，因为这个proxy不是给你在浏览器里面访问的，是要把部署成功后的那个域名`https://xxx.vercel.app`填到这个项目里面的`API_BASE_URL`环境变量中，然后还要再redeploy一次你的gemini pro chat

**Comment by hprandom** [comment]
谢谢，前面加了"https://"就可以了。
