### ISSUE TITLE
Qualifying the vercel edge network region

### ISSUE THREAD

**Issue by xiaoWangSec** [babaohuang/GeminiProChat#72]
### Describe the feature

Is it possible to bypass the issue of 'User location is not supported for the API use.' by qualifying the vercel edge network region?
docs from vercel: [https://vercel.com/docs/edge-network/regions#region-list](https://vercel.com/docs/edge-network/regions#region-list)

### Participation

- [X] I am willing to submit a pull request for this feature.

**Comment by babaohuang** [comment]
I have tried , but astro 2 framwork does not support this feature , we have a solution [here](https://github.com/babaohuang/GeminiProChat#solution-for-user-location-is-not-supported-for-the-api-use)

**Comment by xiaoWangSec** [comment]
OK, I know. 
If I use a Chinese mainland IP or a Singapore IP to access, it is normal; If I use a Hong Kong IP address to access the data, an error message is reported. Add some ruls in proxy software then it works correctly.
Thanks.
