### ISSUE TITLE
Is there a way to maintain the streaming when using palm-proxy

### ISSUE THREAD

**Issue by mantoufan** [babaohuang/GeminiProChat#73]
### Describe the feature

Thanks for your perfect work! I love it so much.  
After I started using a proxy, the typewriter effect of streaming stopped working.   
Is there a way to maintain the streaming?   
It's not necessary to deploy on https://vercel.com, even a tutorial would be great.    

Yup, I just follow these steps, then the typewriter effect of streaming stopped working.
![image](https://github.com/mantoufan/gemini-pro-chat/assets/4961543/72a6149e-b1f0-42ad-a441-bcf6acdcf602)

Thanks @antergone,  I have not found a issues in this repo:
https://github.com/antergone/palm-proxy

### Participation

- [X] I am willing to submit a pull request for this feature.

**Comment by antergone** [comment]
Please provide me with an example that occur error. It would be best if it's a `curl` command.

**Comment by mantoufan** [comment]
@antergone, This isn't an issue with the program. I've been using a service provided by a cloud vendor and the SSE has stopped working through the proxy interface. I'm seeking their help to resolve this. Thanks for your quick response.
