### ISSUE TITLE
docker build出的镜像无法运行

### ISSUE THREAD

**Issue by nice2cu1** [babaohuang/GeminiProChat#8]
### How is Anse deployed?

Docker

### Describe the bug

在Windows下构建的，我用dockerfile和 docker-compose 构建的都没法运行

### Console Logs

dockerfile:
![image](https://github.com/babaohuang/GeminiProChat/assets/33564254/fe94a735-c566-49f4-8e8d-122ee77cb773)
![image](https://github.com/babaohuang/GeminiProChat/assets/33564254/9170a7a5-21a2-43ed-b5e9-9993911fe87d)
docker compose:
![image](https://github.com/babaohuang/GeminiProChat/assets/33564254/d59ccef3-03de-4534-97aa-bfdbc08a8845)
![image](https://github.com/babaohuang/GeminiProChat/assets/33564254/2913c3f7-c8c0-4845-a48e-e39e857bc5a3)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by antergone** [comment]
1. 拉取最新代码，重新构建镜像
2. 执行时，配置环境变量, GEMINI_API_KEY必须配置，API_BASE_URL根据情况配置。

```shell
docker run -d --name GeminiProChat -p 3000:3000 -e GEMINI_API_KEY=AIzaSy1234567890 -e API_BASE_URL=https://palmdemo.vercel.app/ demo_image
```

**Comment by nice2cu1** [comment]
> 1. 拉取最新代码，重新构建镜像
> 2. 执行时，配置环境变量, GEMINI_API_KEY必须配置，API_BASE_URL根据情况配置。
> 
> ```shell
> docker run -d --name GeminiProChat -p 3000:3000 -e GEMINI_API_KEY=AIzaSy1234567890 -e API_BASE_URL=https://palmdemo.vercel.app/ demo_image
> ```

可以了，感谢

**Comment by Eventidus** [comment]
> ```shell
> RL=https://palmdemo.ve
> ```
请教一下最后面的demo_image是哪个

**Comment by antergone** [comment]
> > ```shell
> > RL=https://palmdemo.ve
> > ```
> 
> 请教一下最后面的demo_image是哪个

你自己build出来的那个，也就是docker build -t {image_name}  这里的`image_name` , docker相关的操作，自行通过搜索引擎学习
