### ISSUE TITLE
Vercel Edge Functions: set one or more preferred regions

### ISSUE THREAD

**Issue by lwd-temp** [babaohuang/GeminiProChat#9]
### Describe the feature

https://vercel.com/docs/functions/configuring-functions/region

For Edge Functions:

* By default Edge Functions execute in the region closest to the incoming request
* You can set one or more preferred regions using the route segment [config](https://vercel.com/docs/functions/configuring-functions/region#setting-regions-in-your-function) `preferredRegions` or specify a `regions` key within a config object to set one or more regions for you functions to execute in

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by babaohuang** [comment]
I have tried it , but i didn't work , maybe the Astro 2 doesn't support this feature ?

**Comment by lwd-temp** [comment]
I'm afraid not. Next.js is by Vercel, so there's an official support.

We could have rewritten the request function using the following method:

```typescript
import type { VercelRequest, VercelResponse } from '@vercel/node';
 
export const config = {
  runtime: 'edge', // this is a pre-requisite
  // execute this function on iad1 or hnd1, based on the connecting client location
  regions: ['iad1', 'hnd1'],
};
 
export default function handler(
  request: VercelRequest,
  response: VercelResponse,
) {
  return response.status(200).json({
    text: `I am an Edge Function! (executed on ${process.env.VERCEL_REGION})`,
  });
}
```

But because it is actually wrapped in @google/generative-ai, we cannot modify it.

**Comment by babaohuang** [comment]
> I'm afraid not. Next.js is by Vercel, so there's an official support.
> 
> We could have rewritten the request function using the following method:
> 
> ```ts
> import type { VercelRequest, VercelResponse } from '@vercel/node';
>  
> export const config = {
>   runtime: 'edge', // this is a pre-requisite
>   // execute this function on iad1 or hnd1, based on the connecting client location
>   regions: ['iad1', 'hnd1'],
> };
>  
> export default function handler(
>   request: VercelRequest,
>   response: VercelResponse,
> ) {
>   return response.status(200).json({
>     text: `I am an Edge Function! (executed on ${process.env.VERCEL_REGION})`,
>   });
> }
> ```
> 
> But because it is actually wrapped in @google/generative-ai, we cannot modify it.

but this project is not base on Next.js framework

**Comment by lwd-temp** [comment]
Yes, so we may try the "Other frameworks" example, but we have to refrain from using @google/generative-ai and must rewrite the functionalities it provides on our own.

**Comment by babaohuang** [comment]
now this issue has a perfect solution now , see [here](https://github.com/babaohuang/GeminiProChat#solution-for-user-location-is-not-supported-for-the-api-use)

**Comment by lwd-temp** [comment]
Thank you for your efforts.

Just a kindly reminder, proxies are not allowed in Vercel Fair Use Policy, though Vercel seldom intervenes in these matters.
